//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posy.V2.Infra.CrossCutting.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Posy.V2.Infra.CrossCutting.Common.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome para url inválido.
        /// </summary>
        public static string AliasInvalido {
            get {
                return ResourceManager.GetString("AliasInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amizade inválida.
        /// </summary>
        public static string AmizadeInvalida {
            get {
                return ResourceManager.GetString("AmizadeInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto da imagem incorreto.
        /// </summary>
        public static string CaptchaInvalido {
            get {
                return ResourceManager.GetString("CaptchaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria inválida.
        /// </summary>
        public static string CategoriaInvalida {
            get {
                return ResourceManager.GetString("CategoriaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário não encontrado.
        /// </summary>
        public static string ComentarioNaoEncontrado {
            get {
                return ResourceManager.GetString("ComentarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias já existe.
        /// </summary>
        public static string ComunidadeAliasJaExiste {
            get {
                return ResourceManager.GetString("ComunidadeAliasJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunidade inválida.
        /// </summary>
        public static string ComunidadeInvalida {
            get {
                return ResourceManager.GetString("ComunidadeInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunidade não encontrada.
        /// </summary>
        public static string ComunidadeNaoEncontrada {
            get {
                return ResourceManager.GetString("ComunidadeNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de senha inválida.
        /// </summary>
        public static string ConfirmacaoSenhaInvalida {
            get {
                return ResourceManager.GetString("ConfirmacaoSenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciais inválidas.
        /// </summary>
        public static string CredenciaisInvalidas {
            get {
                return ResourceManager.GetString("CredenciaisInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento inválida.
        /// </summary>
        public static string DataNascimentoInvalida {
            get {
                return ResourceManager.GetString("DataNascimentoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDD Inválido.
        /// </summary>
        public static string DDDInvalido {
            get {
                return ResourceManager.GetString("DDDInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depoimento não encontrado.
        /// </summary>
        public static string DepoimentoNaoEncontrado {
            get {
                return ResourceManager.GetString("DepoimentoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário com este e-mail.
        /// </summary>
        public static string EmailDuplicado {
            get {
                return ResourceManager.GetString("EmailDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido.
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível efetuar o comentário.
        /// </summary>
        public static string ErroAoEnviarComentario {
            get {
                return ResourceManager.GetString("ErroAoEnviarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao excluir o comentário.
        /// </summary>
        public static string ErroAoExcluirComentario {
            get {
                return ResourceManager.GetString("ErroAoExcluirComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao configurar a foto do perfil.
        /// </summary>
        public static string ErroConfiguracaoFotoPerfil {
            get {
                return ResourceManager.GetString("ErroConfiguracaoFotoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de configuração de propriedade.
        /// </summary>
        public static string ErroConfiguracaoPropriedade {
            get {
                return ResourceManager.GetString("ErroConfiguracaoPropriedade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado civil inválido.
        /// </summary>
        public static string EstadoCivilInvalido {
            get {
                return ResourceManager.GetString("EstadoCivilInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão inválida.
        /// </summary>
        public static string ExclusaoInvalida {
            get {
                return ResourceManager.GetString("ExclusaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum comentário informado.
        /// </summary>
        public static string NenhumComentarioInformado {
            get {
                return ResourceManager.GetString("NenhumComentarioInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum depoimento informado.
        /// </summary>
        public static string NenhumDepoimentoInformado {
            get {
                return ResourceManager.GetString("NenhumDepoimentoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum post informado.
        /// </summary>
        public static string NenhumPostInformado {
            get {
                return ResourceManager.GetString("NenhumPostInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum recado informado.
        /// </summary>
        public static string NenhumRecadoInformado {
            get {
                return ResourceManager.GetString("NenhumRecadoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome inválido.
        /// </summary>
        public static string NomeInvalido {
            get {
                return ResourceManager.GetString("NomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve conter no máximo 15 caracteres.
        /// </summary>
        public static string NomeInvalidoTamanho {
            get {
                return ResourceManager.GetString("NomeInvalidoTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do usuário deve ser fornecido.
        /// </summary>
        public static string OIDDoUsuarioDeveSerFornecido {
            get {
                return ResourceManager.GetString("OIDDoUsuarioDeveSerFornecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País inválido.
        /// </summary>
        public static string PaisInvalido {
            get {
                return ResourceManager.GetString("PaisInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil não encontrado.
        /// </summary>
        public static string PerfilNaoEncontrado {
            get {
                return ResourceManager.GetString("PerfilNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil visitado inválido.
        /// </summary>
        public static string PerfilVisitadoInvalido {
            get {
                return ResourceManager.GetString("PerfilVisitadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O perfil visitante não pode ser igual ao perfil visitado.
        /// </summary>
        public static string PerfilVisitanteIgualPerfilVisitado {
            get {
                return ResourceManager.GetString("PerfilVisitanteIgualPerfilVisitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil visitante inválido.
        /// </summary>
        public static string PerfilVisitanteInvalido {
            get {
                return ResourceManager.GetString("PerfilVisitanteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post inválido.
        /// </summary>
        public static string PostInvalido {
            get {
                return ResourceManager.GetString("PostInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recado inválido.
        /// </summary>
        public static string RecadoInvalido {
            get {
                return ResourceManager.GetString("RecadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida.
        /// </summary>
        public static string SenhaInvalida {
            get {
                return ResourceManager.GetString("SenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas digitadas não coincidem.
        /// </summary>
        public static string SenhasNaoCoincidem {
            get {
                return ResourceManager.GetString("SenhasNaoCoincidem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo inválido.
        /// </summary>
        public static string SexoInvalido {
            get {
                return ResourceManager.GetString("SexoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome inválido.
        /// </summary>
        public static string SobrenomeInvalido {
            get {
                return ResourceManager.GetString("SobrenomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sobrenome deve conter no máximo 15 caracteres.
        /// </summary>
        public static string SobrenomeInvalidoTamanho {
            get {
                return ResourceManager.GetString("SobrenomeInvalidoTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de amizade inválida.
        /// </summary>
        public static string SolicitacaoAmizadeInvalida {
            get {
                return ResourceManager.GetString("SolicitacaoAmizadeInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma solicitação de amizade já foi enviada.
        /// </summary>
        public static string SolicitacaoAmizadeJaEnviada {
            get {
                return ResourceManager.GetString("SolicitacaoAmizadeJaEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone inválido.
        /// </summary>
        public static string TelefoneInvalido {
            get {
                return ResourceManager.GetString("TelefoneInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo inválido.
        /// </summary>
        public static string TipoInvalido {
            get {
                return ResourceManager.GetString("TipoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url inválida.
        /// </summary>
        public static string UrlInvalida {
            get {
                return ResourceManager.GetString("UrlInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inválido.
        /// </summary>
        public static string UsuarioInvalido {
            get {
                return ResourceManager.GetString("UsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string UsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vídeo inválido.
        /// </summary>
        public static string VideoInvalido {
            get {
                return ResourceManager.GetString("VideoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vídeo não encontrado.
        /// </summary>
        public static string VideoNaoEncontrado {
            get {
                return ResourceManager.GetString("VideoNaoEncontrado", resourceCulture);
            }
        }
    }
}
