//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posy.V2.Infra.CrossCutting.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIConfigLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIConfigLogin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Posy.V2.Infra.CrossCutting.Common.Resources.UIConfigLogin", typeof(UIConfigLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Telefone.
        /// </summary>
        public static string AdicionarTelefone {
            get {
                return ResourceManager.GetString("AdicionarTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicione um número.
        /// </summary>
        public static string AdicioneUmNumero {
            get {
                return ResourceManager.GetString("AdicioneUmNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar as configurações da sua conta.
        /// </summary>
        public static string AlterarAsSuasConfiguracoesDeConta {
            get {
                return ResourceManager.GetString("AlterarAsSuasConfiguracoesDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string Ano {
            get {
                return ResourceManager.GetString("Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A segunda validação foi enviada.
        /// </summary>
        public static string ASegundaValidacaoFoiEnviada {
            get {
                return ResourceManager.GetString("ASegundaValidacaoFoiEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha foi alterada.
        /// </summary>
        public static string ASenhaFoiAlterada {
            get {
                return ResourceManager.GetString("ASenhaFoiAlterada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha foi enviada.
        /// </summary>
        public static string ASenhaFoiEnviada {
            get {
                return ResourceManager.GetString("ASenhaFoiEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas não se coincidem.
        /// </summary>
        public static string AsSenhasNaoSeCoincidem {
            get {
                return ResourceManager.GetString("AsSenhasNaoSeCoincidem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associe sua conta {0}.
        /// </summary>
        public static string AssocieSuaSocialConta {
            get {
                return ResourceManager.GetString("AssocieSuaSocialConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticação de dois fatores.
        /// </summary>
        public static string AutenticacaoDeDoisFatores {
            get {
                return ResourceManager.GetString("AutenticacaoDeDoisFatores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticação de dois fatores está desabilitado.
        /// </summary>
        public static string AutenticacaoDeDoisFatoresEstaDesabilitado {
            get {
                return ResourceManager.GetString("AutenticacaoDeDoisFatoresEstaDesabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticação de dois fatores está habilitado.
        /// </summary>
        public static string AutenticacaoDeDoisFatoresEstaHabilitado {
            get {
                return ResourceManager.GetString("AutenticacaoDeDoisFatoresEstaHabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente(s) Conectado(s).
        /// </summary>
        public static string ClienteConectados {
            get {
                return ResourceManager.GetString("ClienteConectados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clique aqui para efetuar login.
        /// </summary>
        public static string CliqueAquiParaEfetuarLogin {
            get {
                return ResourceManager.GetString("CliqueAquiParaEfetuarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectar.
        /// </summary>
        public static string Conectar {
            get {
                return ResourceManager.GetString("Conectar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectar com.
        /// </summary>
        public static string ConectarCom {
            get {
                return ResourceManager.GetString("ConectarCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Senha.
        /// </summary>
        public static string ConfirmarSenha {
            get {
                return ResourceManager.GetString("ConfirmarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você autenticou com sucesso com &lt;strong&gt;{0}&lt;/strong&gt;. Por favor, insira um nome de usuário para este site abaixo e clique no botão registrar para concluir o login..
        /// </summary>
        public static string ContaSocialSucessoInfo {
            get {
                return ResourceManager.GetString("ContaSocialSucessoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crie uma nova senha.
        /// </summary>
        public static string CrieUmaNovaSenha {
            get {
                return ResourceManager.GetString("CrieUmaNovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string DataDeNascimento {
            get {
                return ResourceManager.GetString("DataDeNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir senha para conta local.
        /// </summary>
        public static string DefinirSenhaParaContaLocal {
            get {
                return ResourceManager.GetString("DefinirSenhaParaContaLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitar.
        /// </summary>
        public static string Desabilitar {
            get {
                return ResourceManager.GetString("Desabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu código de segurança.
        /// </summary>
        public static string DigiteSeuCodigoDeSeguranca {
            get {
                return ResourceManager.GetString("DigiteSeuCodigoDeSeguranca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efetuar Login.
        /// </summary>
        public static string EfetuarLogin {
            get {
                return ResourceManager.GetString("EfetuarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor confirme sua conta clicando neste link: &lt;a href=&quot;{0}&quot;&gt;&lt;/a&gt;.
        /// </summary>
        public static string EmailMessage {
            get {
                return ResourceManager.GetString("EmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor altere sua senha clicando &lt;a href=&apos;{0}&apos;&gt;aqui&lt;/a&gt;.
        /// </summary>
        public static string EmailMessageEsqueciMinhaSenha {
            get {
                return ResourceManager.GetString("EmailMessageEsqueciMinhaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme sua Conta.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme sua conta - Reenviado.
        /// </summary>
        public static string EmailSubjectResend {
            get {
                return ResourceManager.GetString("EmailSubjectResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar código de verificação.
        /// </summary>
        public static string EnviarCodigoDeVerificacao {
            get {
                return ResourceManager.GetString("EnviarCodigoDeVerificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esquecer Browser.
        /// </summary>
        public static string EsquecerBrowser {
            get {
                return ResourceManager.GetString("EsquecerBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceu sua senha?.
        /// </summary>
        public static string EsqueceuSuaSenha {
            get {
                return ResourceManager.GetString("EsqueceuSuaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci minha senha.
        /// </summary>
        public static string EsqueciMinhaSenha {
            get {
                return ResourceManager.GetString("EsqueciMinhaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string EstadoCivil {
            get {
                return ResourceManager.GetString("EstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao adicionar telefone.
        /// </summary>
        public static string FalhaAoAdicionarTelefone {
            get {
                return ResourceManager.GetString("FalhaAoAdicionarTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário de Associação.
        /// </summary>
        public static string FormularioDeAssociacao {
            get {
                return ResourceManager.GetString("FormularioDeAssociacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forneça seu e-mail.
        /// </summary>
        public static string FornecaSeuEmail {
            get {
                return ResourceManager.GetString("FornecaSeuEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar.
        /// </summary>
        public static string Gerenciar {
            get {
                return ResourceManager.GetString("Gerenciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar.
        /// </summary>
        public static string Habilitar {
            get {
                return ResourceManager.GetString("Habilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o texto da imagem.
        /// </summary>
        public static string InformeoTextoDaImagem {
            get {
                return ResourceManager.GetString("InformeoTextoDaImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar Browser.
        /// </summary>
        public static string LembrarBrowser {
            get {
                return ResourceManager.GetString("LembrarBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar login?.
        /// </summary>
        public static string LembrarLogin {
            get {
                return ResourceManager.GetString("LembrarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha de login.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou Senha incorretos.
        /// </summary>
        public static string LoginOuSenhaIncorretos {
            get {
                return ResourceManager.GetString("LoginOuSenhaIncorretos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins Externos.
        /// </summary>
        public static string LoginsExternos {
            get {
                return ResourceManager.GetString("LoginsExternos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins Sociais.
        /// </summary>
        public static string LoginsSociais {
            get {
                return ResourceManager.GetString("LoginsSociais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça o login usando sua conta {0}.
        /// </summary>
        public static string LogInUsingYourProviderAccount {
            get {
                return ResourceManager.GetString("LogInUsingYourProviderAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mês.
        /// </summary>
        public static string Mes {
            get {
                return ResourceManager.GetString("Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de telefone.
        /// </summary>
        public static string NumeroDeTelefone {
            get {
                return ResourceManager.GetString("NumeroDeTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O browser NÃO será lembrado para Two Factor.
        /// </summary>
        public static string OBrowserNaoSeraLembradoParaTwoFactor {
            get {
                return ResourceManager.GetString("OBrowserNaoSeraLembradoParaTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O browser será lembrado para Two Factor.
        /// </summary>
        public static string OBrowserSeraLembradoParaTwoFactor {
            get {
                return ResourceManager.GetString("OBrowserSeraLembradoParaTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código de segurança é.
        /// </summary>
        public static string OCodigoDeSegurancaE {
            get {
                return ResourceManager.GetString("OCodigoDeSegurancaE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro.
        /// </summary>
        public static string OcorreuUmErro {
            get {
                return ResourceManager.GetString("OcorreuUmErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Login foi removido.
        /// </summary>
        public static string OLoginFoiRemovido {
            get {
                return ResourceManager.GetString("OLoginFoiRemovido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Telefone foi adicionado.
        /// </summary>
        public static string OTelefoneFoiAdicionado {
            get {
                return ResourceManager.GetString("OTelefoneFoiAdicionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Telefone foi removido.
        /// </summary>
        public static string OTelefoneFoiRemovido {
            get {
                return ResourceManager.GetString("OTelefoneFoiRemovido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor.
        /// </summary>
        public static string PorFavor {
            get {
                return ResourceManager.GetString("PorFavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        public static string Registrar {
            get {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar uma nova conta?.
        /// </summary>
        public static string RegistrarUmaNovaConta {
            get {
                return ResourceManager.GetString("RegistrarUmaNovaConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Remover {
            get {
                return ResourceManager.GetString("Remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair de Todos os Lugares.
        /// </summary>
        public static string SairDeTodosOsLugares {
            get {
                return ResourceManager.GetString("SairDeTodosOsLugares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Sexo {
            get {
                return ResourceManager.GetString("Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        public static string Sobrenome {
            get {
                return ResourceManager.GetString("Sobrenome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha foi resetada.
        /// </summary>
        public static string SuaSenhaFoiResetada {
            get {
                return ResourceManager.GetString("SuaSenhaFoiResetada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve ter pelo menos {2} caracteres.
        /// </summary>
        public static string TamanhoDeSenha {
            get {
                return ResourceManager.GetString("TamanhoDeSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trocar.
        /// </summary>
        public static string Trocar {
            get {
                return ResourceManager.GetString("Trocar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trocar de Senha.
        /// </summary>
        public static string TrocarDeSenha {
            get {
                return ResourceManager.GetString("TrocarDeSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login malsucedido com serviço.
        /// </summary>
        public static string UnsuccessfulLoginWithService {
            get {
                return ResourceManager.GetString("UnsuccessfulLoginWithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar número de telefone.
        /// </summary>
        public static string VerificarNumeroDeTelefone {
            get {
                return ResourceManager.GetString("VerificarNumeroDeTelefone", resourceCulture);
            }
        }
    }
}
