//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posy.V2.Infra.CrossCutting.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Posy.V2.Infra.CrossCutting.Common.Resources.UIConfig", typeof(UIConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aceitar.
        /// </summary>
        public static string aceitar {
            get {
                return ResourceManager.GetString("aceitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Amigo.
        /// </summary>
        public static string AdicionarAmigo {
            get {
                return ResourceManager.GetString("AdicionarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agora.
        /// </summary>
        public static string Agora {
            get {
                return ResourceManager.GetString("Agora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando pedido de entrada.
        /// </summary>
        public static string AguardandoPedidoDeEntrada {
            get {
                return ResourceManager.GetString("AguardandoPedidoDeEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar foto da comunidade.
        /// </summary>
        public static string AlterarFotoDaComunidade {
            get {
                return ResourceManager.GetString("AlterarFotoDaComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar foto do perfil.
        /// </summary>
        public static string AlterarFotoDoPerfil {
            get {
                return ResourceManager.GetString("AlterarFotoDoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string Amigos {
            get {
                return ResourceManager.GetString("Amigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos Pendentes.
        /// </summary>
        public static string AmigosPendentes {
            get {
                return ResourceManager.GetString("AmigosPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amizades.
        /// </summary>
        public static string Amizades {
            get {
                return ResourceManager.GetString("Amizades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anterior.
        /// </summary>
        public static string anterior {
            get {
                return ResourceManager.GetString("anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas meus amigos.
        /// </summary>
        public static string ApenasMeusAmigos {
            get {
                return ResourceManager.GetString("ApenasMeusAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string Autor {
            get {
                return ResourceManager.GetString("Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear postagens desse perfil.
        /// </summary>
        public static string BloquearPostagensDessePerfil {
            get {
                return ResourceManager.GetString("BloquearPostagensDessePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunidade.
        /// </summary>
        public static string Comunidade {
            get {
                return ResourceManager.GetString("Comunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunidades.
        /// </summary>
        public static string Comunidades {
            get {
                return ResourceManager.GetString("Comunidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string Configuracoes {
            get {
                return ResourceManager.GetString("Configuracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criada em.
        /// </summary>
        public static string CriadaEm {
            get {
                return ResourceManager.GetString("CriadaEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Comunidade.
        /// </summary>
        public static string CriarComunidade {
            get {
                return ResourceManager.GetString("CriarComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar tópico.
        /// </summary>
        public static string CriarTopico {
            get {
                return ResourceManager.GetString("CriarTopico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados da Comunidade.
        /// </summary>
        public static string DadosDaComunidade {
            get {
                return ResourceManager.GetString("DadosDaComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Perfil.
        /// </summary>
        public static string DadosDoPerfil {
            get {
                return ResourceManager.GetString("DadosDoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Pessoais.
        /// </summary>
        public static string DadosPessoais {
            get {
                return ResourceManager.GetString("DadosPessoais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string DataDeNascimento {
            get {
                return ResourceManager.GetString("DataDeNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depoimentos.
        /// </summary>
        public static string Depoimentos {
            get {
                return ResourceManager.GetString("Depoimentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do tópico.
        /// </summary>
        public static string DescricaoDoTopico {
            get {
                return ResourceManager.GetString("DescricaoDoTopico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dia atrás.
        /// </summary>
        public static string diaatras {
            get {
                return ResourceManager.GetString("diaatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dias atrás.
        /// </summary>
        public static string diasatras {
            get {
                return ResourceManager.GetString("diasatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dono.
        /// </summary>
        public static string Dono {
            get {
                return ResourceManager.GetString("Dono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dono da Comunidade.
        /// </summary>
        public static string DonoDaComunidade {
            get {
                return ResourceManager.GetString("DonoDaComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Comunidade.
        /// </summary>
        public static string EditarComunidade {
            get {
                return ResourceManager.GetString("EditarComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Perfil.
        /// </summary>
        public static string EditarPerfil {
            get {
                return ResourceManager.GetString("EditarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar na comunidade.
        /// </summary>
        public static string EntrarNaComunidade {
            get {
                return ResourceManager.GetString("EntrarNaComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando.
        /// </summary>
        public static string Esperando {
            get {
                return ResourceManager.GetString("Esperando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string EstadoCivil {
            get {
                return ResourceManager.GetString("EstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string excluir {
            get {
                return ResourceManager.GetString("excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir comentário.
        /// </summary>
        public static string ExcluirComentário {
            get {
                return ResourceManager.GetString("ExcluirComentário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Comunidade.
        /// </summary>
        public static string ExcluirComunidade {
            get {
                return ResourceManager.GetString("ExcluirComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir postagem.
        /// </summary>
        public static string ExcluirPostagem {
            get {
                return ResourceManager.GetString("ExcluirPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir postagens selecionadas.
        /// </summary>
        public static string ExcluirPostagensSelecionadas {
            get {
                return ResourceManager.GetString("ExcluirPostagensSelecionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir recado.
        /// </summary>
        public static string Excluirrecado {
            get {
                return ResourceManager.GetString("Excluirrecado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir recados selecionados.
        /// </summary>
        public static string ExcluirRecadosSelecionados {
            get {
                return ResourceManager.GetString("ExcluirRecadosSelecionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixo.
        /// </summary>
        public static string Fixo {
            get {
                return ResourceManager.GetString("Fixo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórum.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto da Comunidade.
        /// </summary>
        public static string FotoDaComunidade {
            get {
                return ResourceManager.GetString("FotoDaComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto do Perfil.
        /// </summary>
        public static string FotoDoPerfil {
            get {
                return ResourceManager.GetString("FotoDoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frase do perfil.
        /// </summary>
        public static string FraseDoPerfil {
            get {
                return ResourceManager.GetString("FraseDoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hora atrás.
        /// </summary>
        public static string horaatras {
            get {
                return ResourceManager.GetString("horaatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horas atrás.
        /// </summary>
        public static string horasatras {
            get {
                return ResourceManager.GetString("horasatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membros.
        /// </summary>
        public static string Membros {
            get {
                return ResourceManager.GetString("Membros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membros Pendentes.
        /// </summary>
        public static string MembrosPendentes {
            get {
                return ResourceManager.GetString("MembrosPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Depoimentos.
        /// </summary>
        public static string MeusDepoimentos {
            get {
                return ResourceManager.GetString("MeusDepoimentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Recados.
        /// </summary>
        public static string MeusRecados {
            get {
                return ResourceManager.GetString("MeusRecados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Vídeos.
        /// </summary>
        public static string MeusVideos {
            get {
                return ResourceManager.GetString("MeusVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minhas Comunidades.
        /// </summary>
        public static string MinhasComunidades {
            get {
                return ResourceManager.GetString("MinhasComunidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minuto atrás.
        /// </summary>
        public static string minutoatras {
            get {
                return ResourceManager.GetString("minutoatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutos atrás.
        /// </summary>
        public static string minutosatras {
            get {
                return ResourceManager.GetString("minutosatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderador da Comunidade.
        /// </summary>
        public static string ModeradorDaComunidade {
            get {
                return ResourceManager.GetString("ModeradorDaComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderadores.
        /// </summary>
        public static string Moderadores {
            get {
                return ResourceManager.GetString("Moderadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não fixo.
        /// </summary>
        public static string NaoFixo {
            get {
                return ResourceManager.GetString("NaoFixo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Comunidade.
        /// </summary>
        public static string NomeDaComunidade {
            get {
                return ResourceManager.GetString("NomeDaComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do tópico.
        /// </summary>
        public static string NomeDoTopico {
            get {
                return ResourceManager.GetString("NomeDoTopico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome para url amigável.
        /// </summary>
        public static string NomeParaUrlAmigavel {
            get {
                return ResourceManager.GetString("NomeParaUrlAmigavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar postagem.
        /// </summary>
        public static string OcultarPostagem {
            get {
                return ResourceManager.GetString("OcultarPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string Pagina {
            get {
                return ResourceManager.GetString("Pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para.
        /// </summary>
        public static string Para {
            get {
                return ResourceManager.GetString("Para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil da Comunidade.
        /// </summary>
        public static string PerfilDaComunidade {
            get {
                return ResourceManager.GetString("PerfilDaComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoas.
        /// </summary>
        public static string Pessoas {
            get {
                return ResourceManager.GetString("Pessoas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primeiro.
        /// </summary>
        public static string primeiro {
            get {
                return ResourceManager.GetString("primeiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacidade.
        /// </summary>
        public static string Privacidade {
            get {
                return ResourceManager.GetString("Privacidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privada.
        /// </summary>
        public static string Privada {
            get {
                return ResourceManager.GetString("Privada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to próximo.
        /// </summary>
        public static string proximo {
            get {
                return ResourceManager.GetString("proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pública.
        /// </summary>
        public static string Publica {
            get {
                return ResourceManager.GetString("Publica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quem pode escrever recados para mim?.
        /// </summary>
        public static string QuemPodeEscreverRecadosParaMim {
            get {
                return ResourceManager.GetString("QuemPodeEscreverRecadosParaMim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quem pode ver meus recados?.
        /// </summary>
        public static string QuemPodeVerMeusRecados {
            get {
                return ResourceManager.GetString("QuemPodeVerMeusRecados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recados.
        /// </summary>
        public static string Recados {
            get {
                return ResourceManager.GetString("Recados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recusar.
        /// </summary>
        public static string recusar {
            get {
                return ResourceManager.GetString("recusar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacionamentos.
        /// </summary>
        public static string Relacionamentos {
            get {
                return ResourceManager.GetString("Relacionamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Amigo.
        /// </summary>
        public static string RemoverAmigo {
            get {
                return ResourceManager.GetString("RemoverAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair da Comunidade.
        /// </summary>
        public static string SairDaComunidade {
            get {
                return ResourceManager.GetString("SairDaComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Dados da Comunidade.
        /// </summary>
        public static string SalvarDadosDaComunidade {
            get {
                return ResourceManager.GetString("SalvarDadosDaComunidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar dados de privacidade.
        /// </summary>
        public static string SalvarDadosDePrivacidade {
            get {
                return ResourceManager.GetString("SalvarDadosDePrivacidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Dados Pessoais.
        /// </summary>
        public static string SalvarDadosPessoais {
            get {
                return ResourceManager.GetString("SalvarDadosPessoais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar tópico.
        /// </summary>
        public static string SalvarTopico {
            get {
                return ResourceManager.GetString("SalvarTopico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar vídeo.
        /// </summary>
        public static string SalvarVideo {
            get {
                return ResourceManager.GetString("SalvarVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundo atrás.
        /// </summary>
        public static string segundoatras {
            get {
                return ResourceManager.GetString("segundoatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundos atrás.
        /// </summary>
        public static string segundosatras {
            get {
                return ResourceManager.GetString("segundosatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Sexo {
            get {
                return ResourceManager.GetString("Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        public static string Sobrenome {
            get {
                return ResourceManager.GetString("Sobrenome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as atualizações.
        /// </summary>
        public static string TodasAsAtualizacoes {
            get {
                return ResourceManager.GetString("TodasAsAtualizacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tópicos.
        /// </summary>
        public static string topicos {
            get {
                return ResourceManager.GetString("topicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to último.
        /// </summary>
        public static string ultimo {
            get {
                return ResourceManager.GetString("ultimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Post.
        /// </summary>
        public static string UltimoPost {
            get {
                return ResourceManager.GetString("UltimoPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL do Vídeo.
        /// </summary>
        public static string UrlDoVideo {
            get {
                return ResourceManager.GetString("UrlDoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver mais comentários.
        /// </summary>
        public static string VerMaisComentarios {
            get {
                return ResourceManager.GetString("VerMaisComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver menos comentários.
        /// </summary>
        public static string VerMenosComentarios {
            get {
                return ResourceManager.GetString("VerMenosComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver último.
        /// </summary>
        public static string VerUltimo {
            get {
                return ResourceManager.GetString("VerUltimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vídeos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitantes do perfil.
        /// </summary>
        public static string Visitantesdoperfil {
            get {
                return ResourceManager.GetString("Visitantesdoperfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você ainda não aceitou este depoimento.
        /// </summary>
        public static string VoceAindaNaoAceitouEsteDepoimento {
            get {
                return ResourceManager.GetString("VoceAindaNaoAceitouEsteDepoimento", resourceCulture);
            }
        }
    }
}
